# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f284e3742857972dd1d3d96fb4abb6f0cd50ea8f2b18a399c856edefd954679061977d2679aaa01cb4cbf1300ae9bc300f9c468ee51327cbb5e939369f374d47

test:
  secret_key_base: 4799f49e4d2bc7a1e8c0bd3c4f13bfd4fe3798f8552d9930f123510a662bac4155c2592bfb5dfe7a1598cecf11d03b38fb61a808fd479d966eb767a04028176d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
